In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('move-data.csv', sep=',')

In [3]:
df

,Index,Name,Type,Category,Contest,PP,Power,Accuracy,Generation
0,1,Pound,Normal,Physical,Tough,35,40,100,1
1,2,Karate Chop,Fighting,Physical,Tough,25,50,100,1
2,3,Double Slap,Normal,Physical,Cute,10,15,85,1
3,4,Comet Punch,Normal,Physical,Tough,15,18,85,1
4,5,Mega Punch,Normal,Physical,Tough,20,80,85,1
...,...,...,...,...,...,...,...,...,...
723,724,Searing Sunraze Smash,Steel,Special,???,1,200,None,7
724,725,Menacing Moonraze Maelstrom,Ghost,Special,???,1,200,None,7
725,726,Let's Snuggle Forever,Fairy,Physical,???,1,190,None,7
726,727,Splintered Stormshards,Rock,Physical,???,1,190,None,7
727,728,Clangorous Soulblaze,Dragon,Special,???,1,185,None,7

In [33]:
export = df[['Name','Type', 'PP', 'Power', 'Accuracy']]
export = export.loc[df['Category'] == 'Physical']
export = export.loc[(df['Accuracy'] != 'None') & (df['Power'] != 'None')]

In [34]:
export.to_csv(path_or_buf = "move-data-clean.csv")

In [35]:
export

                Name      Type  PP Power Accuracy
0              Pound    Normal  35    40      100
1        Karate Chop  Fighting  25    50      100
2        Double Slap    Normal  10    15       85
3        Comet Punch    Normal  15    18       85
4         Mega Punch    Normal  20    80       85
..               ...       ...  ..   ...      ...
711   Spectral Thief     Ghost  10    90      100
712  Sunsteel Strike     Steel   5   100      100
715         Zing Zap  Electric  10    80      100
717     Multi-Attack    Normal  10    90      100
720     Plasma Fists  Electric  15   100      100

[218 rows x 5 columns]